tugas = float(input("Nilai tugas: "))
uts = float(input("Nilai UTS: "))
uas = float(input("Nilai UAS: "))
kehadiran = float(input("Kehadiran (%): "))
penghasilan = int(input("Penghasilan ortu: "))
jum_serf = int(input("Jumlah sertifikat: "))
akhir = (tugas * 20/100) + (uts * 35/100) + (uas * 45/100)
print(f"Nilai Akhir : {akhir:.1f}")
int_valid = (tugas <=100 and tugas >= 65) or  (uts <= 100 and uts >= 65) or (uas <= 100 and uas >= 65) and (kehadiran >= 85) and (penghasilan <= 4000000 and penghasilan >=0) or (jum_serf >= 2)
print(f"Input valid : {int_valid}")
print(f"Status : {int_valid and "LAYAK" or "TIDAK LAYAK"}")